samples:
  Pitch-6-MWP__deamSim__1000000: input-data/Pitch-6_deamSim.fa.gz.NC_012920.1_genomic.fna.sort.MWP.bam
  Pitch-6-AFG__deamSim__1000000: input-data/Pitch-6_deamSim.fa.gz.NC_012920.1_genomic.fna.sort.AFG.bam
metaDMG_cpp: ./metaDMG-cpp
names: names.dmp
nodes: nodes.dmp
acc2tax: acc2taxid.map.gz
min_similarity_score: 0.95
max_similarity_score: 1.0
min_mapping_quality: 0
lca_rank: ""
max_position: 15
min_reads: 0
weight_type: 1
custom_database: true
forward_only: false
output_dir: data-mapping
parallel_samples: 1
cores_per_sample: 1
bayesian: true
config_file: config_mapping.yaml
damage_mode: local
version: 0.27.2
